# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Qodo Suggest Tests

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
        pip install -e .
    - name: Test with unittest
      run: |
        cd tests/
        python -m unittest discover ./
        cd ../
    - name: Suggest Tests with Qodo
      uses: qodo-ai/qodo-ci/.github/actions/qodo-cover@v0.1.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        project_language: python
        project_root: ./
        code_coverage_report_path: ./tests/coverage.xml
        test_command: "cd tests/ && coverage run -m unittest discover ./ && coverage xml -o coverage.xml && cd ../"
        model: gpt-4o

      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}